#!/usr/bin/env bash
# Script to display information about subdomains of a domain

get_record_info() {
    local domain=$1
    local subdomain=$2
    local record_type=$3
    local destination=$4
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

audit_subdomain() {
    local domain=$1
    local subdomain=$2

    dig_output=$(dig "$subdomain.$domain" | awk '/^;; ANSWER SECTION:$/,/^$/ {print}')
    record_type=$(echo "$dig_output" | awk '$4 == "IN" {print $3}')
    destination=$(echo "$dig_output" | awk '$4 == "A" {print $5}')

    get_record_info "$domain" "$subdomain" "$record_type" "$destination"
}

audit_domain() {
    local domain=$1
    subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${subdomains[@]}"; do
        audit_subdomain "$domain" "$subdomain"
    done
}

main() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        audit_domain "$domain"
    else
        audit_subdomain "$domain" "$subdomain"
    fi
}

main "$@"

