#!/usr/bin/env bash
# This script displays the username, user ID, and home directory path for users in /etc/passwd.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
