#!/usr/bin/env bash
# This bash script displays "Best School" 10 times, and 
# for the 9th iteration, it says "Hi" on a ne

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
